usda_api_key = "iH4IGk3WBmaLDF5OAvlaXcmBj8akrONtXAtK0TH5"

[connections.supabase]
SUPABASE_URL = "https://rgfhrhvdspwlexlymdga.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJnZmhyaHZkc3B3bGV4bHltZGdhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEzODg2ODEsImV4cCI6MjA1Njk2NDY4MX0.P_hdynXVGULdvy-fKeBMkNAMsm83bK8v-027jyA6Ohs"

[general]
openai_api_key = "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"